# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from home import Ui_Home
from read import Ui_Read
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi
import os
import os.path
from os import listdir
from os.path import isfile, join
from gl import *
from db import *

db_file = 'storage.db'

class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(198, 100, 106);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(190, 70, 441, 441))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 170, 241, 16))
        self.label.setObjectName("label")
        self.masterPasswordVieja = QtWidgets.QTextEdit(self.frame)
        self.masterPasswordVieja.setGeometry(QtCore.QRect(70, 190, 301, 31))
        self.masterPasswordVieja.setStyleSheet("")
        self.masterPasswordVieja.setObjectName("masterPassword")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 281, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("logo.jpeg"))
        self.label_2.setObjectName("label_2")
        self.ingresarViejo = QtWidgets.QPushButton(self.frame)
        self.ingresarViejo.setGeometry(QtCore.QRect(170, 230, 113, 32))
        self.ingresarViejo.setStyleSheet("background-color: rgb(198, 100, 106);\n"
"color: rgb(255, 255, 255);")
        self.ingresarViejo.setObjectName("ingresarViejo")
        self.masterPasswordVieja.raise_()
        self.ingresarViejo.raise_()
        self.ingresarViejo.clicked.connect(self.openHome)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Contraseña Maestra"))
        self.ingresarViejo.setText(_translate("MainWindow", "Ingresar"))

    def openHome(self):
        if os.path.isfile(db_file):

            password = self.masterPasswordVieja.toPlainText()
            #TODO - encriptar el password
            ep = encryptMainPass(password)
            
            #TODO - confirmar el password en la db
            if login(ep):
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_Home()
                self.ui.setupUi(self.window)
                Login.hide()
                self.window.show()
            else:
                print("password incorrecto")

        else:
            password = self.masterPasswordVieja.toPlainText()
            #encripta el password principal
            ep = encryptMainPass(password)

            register(ep)
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_Home()
            self.ui.setupUi(self.window)
            Login.hide()
            self.window.show()
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
